version: '3.1'

services:

  reactfrontendapp:
    image: react-frontend-app:1.0.0
    ports:
        - '2000:2000'
    restart: always
    depends_on:
        - nodebackendapp

  nodebackendapp:
    image: node-backend-app:1.0.0
    ports:
        - '5000:5000'
    restart: always
    depends_on:
        - mysqldb

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Server@2016

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8888:80'
    restart: always
    environment:
        PMA_HOST: mysqldb
    depends_on:
        - mysqldb
